### ISSUE TITLE
Niye sadece Readme var ya .d

### ISSUE THREAD

**Issue by ardakaragoz** [asdfg1446/botum#1]

**Comment by asdfg1446** [comment]
s

**Comment by ardakaragoz** [comment]
S derken abi anlamadım ben çok bilmiyom da bu işleri .d

**Comment by asdfg1446** [comment]
bende bilmiyorum deneme amaçlı yaptım

**Comment by ardakaragoz** [comment]
Anladım abi peki bot yapma için ben Saul Goodman diye bir kanal biliyorum onu tavsiye ederim harika kanal valla sahibi de çok tatlıı, beyefendi biri

**Comment by asdfg1446** [comment]
saol bende mental power izliyprum şuan yeni bölümü gelmiş

**Comment by ardakaragoz** [comment]
Valla mı bak sana bir tesadüf söyleyeyim mi ben o kanalın sahibiyim .d neyse ben kapatıyorum tartışmayı sana kolay gelsin abim
